### PR TITLE
Chrishat34s working reserve

### PR DESCRIPTION
**Pull request by 2e0byo**
Chrishat34s changes implementing working reserve. I'm going to leave this PR open for a bit so he can comment on it.

### CODE REVIEW

**Review by 2e0byo — COMMENTED** [review]
@chrishat34 why was this necessary?

**Comment by 2e0byo** [comment]
Other than that I understood everything.  I've:

- refactored slightly, removing globals (that's what classes are for!)
- removed some comments, prints, etc from testing
- cleaned up in a few places
- removed hardcoded notify() code

Could you look over the new version and check you're happy with it?  If so I'll merge.

Also, did you manage to book a test?  How did it go?  [If you didn't I guess you can test this version....]

**Comment by chrishat34** [comment]
> apropos [200ab1d](https://github.com/2e0byo/YADC/commit/200ab1d993e01af11ce971c30fa5357329fd89f7)
> 
> @chrishat34 why was this necessary?
I think it was just a typo s i cleaned things up a little - sorry to confuse

**Comment by chrishat34** [comment]
> 

Hi, I would quite like to talk to you privately more about this if possible i.e. off here, email maybe?

**Comment by chrishat34** [comment]
and the sleeper added to humanlike as:
```python
def sleeper():
    duration = randint(930, 1000)# was 930, 1000
    print(f"Sleeping for {duration} s")
    with Halo(spinner="dots"):
        sleep(duration)
```

**Comment by chrishat34** [comment]
Ok, i had a look through, 2 comments, ref scraper.py:
1. line 250, did you mean to remove the:
        with open("C:\\git\\new\\YADC-master\\yadc\\errors\\tmp\\test.html", "w") as f:
            f.write(page)
2. line 281 ish, the last line with the user input stops the reserve bit running automatically!

**Comment by 2e0byo** [comment]
@chrishat34 my email is (now) on my github profile.  (I'll not put it here in case I remove it later).

Thanks for those comments; I'll factor them in later and then merge this.  Thanks for getting it working!

**Comment by 2e0byo** [comment]
> Ok, i had a look through, 2 comments, ref scraper.py:
> 
> 1. line 250, did you mean to remove the:
>    with open("C:\git\new\YADC-master\yadc\errors\tmp\test.html", "w") as f:
>    f.write(page)

Yes, it was left over from testing; that file is never used (it was just for me to look at).

> 2. line 281 ish, the last line with the user input stops the reserve bit running automatically!

You mean [this line](https://github.com/2e0byo/YADC/pull/5/files#diff-a9ebafc4fd06eacce2d24dae674c4b2dd42f5c1f1b4cf5c14eb694501121ad83R247) ?  It won't run if `self.reserve` isn't set.  However I need to document that and demonstrate it in `main.py`, thanks.

**Comment by chrishat34** [comment]
ok, all cool, thanks

**Comment by 2e0byo** [comment]
> apropos [200ab1d](https://github.com/2e0byo/YADC/commit/200ab1d993e01af11ce971c30fa5357329fd89f7)
> 
> @chrishat34 why was this necessary?

I meant this commit, sorry, but it doesn't do any harm: 2f20200ffc5a1c7f2c12aafb99f64115a74c35ed

**Pull request merged**
