### PR TITLE
feat: my_scratch_code

### PR DESCRIPTION
**Pull request by chrishat34**
```python
import datetime as dt
import warnings
from collections import deque
from datetime import datetime
from logging import getLogger
from random import randint
from time import monotonic, sleep
from typing import Callable

from playsound import playsound
from twilio.rest import Client

from pydantic import BaseModel
from selenium.webdriver import Chrome
from selenium.webdriver.common.by import By

from browser import Browser, BrowserError
from humanlike import randsleep, sleeper
from utils import solve_captcha

search_counter = 0

def twilio_text(msg, test_slot):
    message = f"""
                {msg} A Driving test has been reserved on {test_slot} in reserved_centre  """

    account_sid = ''  
    # auth_token = os.environ["TWILIO_TOKEN"]
    auth_token = ''

    client = Client(account_sid, auth_token)

    message = client.messages.create(
        # body="Join Earth's mightiest heroes. Like Kevin Bacon.",
        body=message,
        from_='',
        to=''
    )
    # print(message.status)
    # print(message)iii


class Test(BaseModel):
    """A driving test."""

    date: datetime
    centre: str


class Centre(BaseModel):
    """A centre and optional before date."""

    centre: str
    date: datetime = None


class Driver(BaseModel):
    "A driver seeking a driving test."
    licence_number: str
    not_before:str
    not_after:str
    client_name_booked: str
    client_name_search: str
    booking_ref: str
    centres: list[Centre]
    not_before: datetime
    not_after: datetime
    disabled_dates: list[datetime] = None
    current_test: Test = None
    refresh_urls: dict = None


class ScraperError(Exception):
    pass


class BookingError(ScraperError):
    pass


class LoginError(Exception):
    pass


class Scraper:
    instances = []
    

    def __init__(
        self,
        browser: Browser,
        drivers: list[Driver],
        notify: Callable = None,
        reserve: bool = True,
        short_notice: bool = True,
    ):
        self._browser = browser
        self.notify = notify or print
        i = max(self.instances) + 1 if self.instances else 1
        self.instances.append(i)
        self.name = f"Browser-{i}"
        self._logger = getLogger(self.name)
        self.drivers = drivers
        for driver in self.drivers:
            driver.refresh_urls = {}
        self._logged_in = False
        self.reserve = reserve
        self.short_notice = short_notice

    @staticmethod
    def dvsa_disabled():
        return datetime.now().time() < dt.time(6) or datetime.now().time() > dt.time(
            23, 30
        )

    @staticmethod
    def input_text_box(el, text):
        for char in text:
            el.send_keys(char)
            randsleep(0.01)

    @staticmethod
    def parse_timestr(timestr: str) -> datetime:
        return datetime.strptime(timestr, "%A %d %B %Y %I:%M%p")

    def logged_in(self, browser) -> bool:
        return (
            self._logged_in
            and "queue" not in browser.current_url
            and "/login" not in browser.page_source
        )

    def login(self, browser: Chrome, driver: Driver):
        if self.logged_in(browser):
            return

        browser.bypass()
        if "queue" in browser.current_url:
            self._logger.info("Queuing...")
        while "queue" in browser.current_url:
            sleep(2)

        randsleep(3)
        browser.bypass()
        print("I'm in - off i go")
        el = browser.find_element(value="driving-licence-number")
        el.click()
        randsleep(1)
        self.input_text_box(el, driver.licence_number)

        el = browser.find_element(value="application-reference-number")
        el.click()
        randsleep(1)
        self.input_text_box(el, driver.booking_ref)

        browser.find_element(value="booking-login").click()
        randsleep(3)

        if "loginError=true" in browser.current_url:
            raise LoginError("Unable to login.")
        self._logged_in = True

    def find_tests(self, browser: Chrome, driver: Driver):
        self.login(browser, driver)
        main = browser.find_element(value="main").get_attribute("innerHTML")
        if "has been cancelled" in main:
            raise ScraperError("Booking Cancelled.")
        elif "has now been exceeded" in main:
            raise ScraperError("Maximum rebookings exceeded.")

        contents_container = browser.find_elements(By.CLASS_NAME, "contents")
        if not contents_container:
            raise ScraperError("Failed to find contents container.")
        # this bit just getting current test date - jch
        date = self.parse_timestr(
            contents_container[0]
            .find_element(By.XPATH, ".//dd")
            .get_attribute("innerHTML")
        )
        # this bit just getting current test centre - jch
        centre = (
            contents_container[1]
            .find_element(By.XPATH, ".//dd")
            .get_attribute("innerHTML")
        )
        # this bit here just getting current test date - jch
        driver.current_test = Test(date=date, centre=centre)
        print(f">>>> Current Booking for {driver.client_name_booked} is on {date} in {centre}")
        print(f">>>> Looking for dates for {driver.client_name_search} between {driver.not_before} and {driver.not_after}")
        for centre in driver.centres:
            randsleep(1.5) #  this is where the wait in between centre checks is

            depth = self.find_next_available(browser, driver, centre)
            for _ in range(depth):
                # this is just going back in the page history on the browser
                randsleep(0.5)
                browser.back()
                # was 0.5

    def get_centre_url(self, browser, centre):
        browser.find_element(value="test-centre-change").click()
        randsleep(3)
        el = browser.find_element(value="test-centres-input")
        el.clear()
        self.input_text_box(el, centre)
        browser.find_element(value="test-centres-submit").click()
        randsleep(5)
        container = browser.find_element(By.CLASS_NAME, "test-centre-results")
        centre = container.find_element(By.XPATH, ".//a")
        return centre.get_attribute("href")

    def find_next_available(self, browser: Chrome, driver: Driver, centre: Centre):
        global search_counter
        randsleep(18)  # was 1.5, was 5 and search limit for the day is reached
        search_counter += 1
        self._logger.info(f"counter = {search_counter} :Trying centre {centre.centre}")
        if centre.centre == driver.current_test.centre:
            back = 2
            browser.find_element(value="date-time-change").click()
            randsleep(1)
            browser.find_element(value="test-choice-earliest").click()
            randsleep(1)
            browser.execute_script("window.scrollTo(0, document.body.scrollHeight);")
            randsleep(1)
            # below is a clickable button
            browser.find_element(value="driving-licence-submit").click()
            randsleep(1)
        else:
            back = 3
            refresh_url = driver.refresh_urls.get(
                centre.centre, self.get_centre_url(browser, centre.centre)
            )
            browser.get(refresh_url)
            randsleep(1)

        page = browser.page_source
        # with open("/tmp/test.html", "w") as f:
        with open("C:\\git\\new\\YADC-master\\yadc\\errors\\tmp\\test.html", "w") as f:
            f.write(page)
        if any(
            x in page
            for x in (
                "Oops",
                "in the queue",
                "Incapsula incident",
                "Enter details below",
                "Search limit reached"
            )
        ):
            browser.bypass()  # is this needed now we handle on getting?

        if "no tests available" in page:
            self._logger.info("No tests available.")
            return back

        day, el = self._scan_for_test(browser, driver, centre)
        if not day:
            self._logger.info(f"Test Found BUT Not in required range of NOT before ???????")
            return back
#ToDo note uncommented return back above if it crashes
        self.notify(f"Test found at {centre} on {day}")
        if self.reserve:
            slot = self._reserve_test(browser, day, el)
            print("i get here in the reserve loop")
            # the following remmed as was getting logger errors and crashed
            # if slot:
            #     self.logger.info(f"Reserved test: {slot}")
            # else:
            #     self.logger.info("Failed to reserve test...")
            #     return back
        return back

    @staticmethod
    def correct_month_showing(browser: Chrome, day: datetime):
        el = browser.find_element(By.CLASS_NAME, "BookingCalendar-currentMonth")
        return day.strftime("%B") in el.get_attribute("innerHTML")

    def _reserve_test(self, browser: Chrome, day: datetime, el) -> bool:
        """Reserve a test.  **UNTESTED**"""
        global test_slot
        warnings.warn(
            "Attempting to reserve test: code untested.  YMMV!", RuntimeWarning
        )

        # scroll to correct month
        attempts = 0
        while not self.correct_month_showing(browser, day):
            
            browser.find_element(By.CLASS_NAME, "BookingCalendar-nav--prev").click()
            attempts += 1
            if attempts > 12:
                raise BookingError("Failed to find correct month.")

        # click on date.
        el.click()
        # get container
        time_container = browser.find_element(By.ID, f"date-{day.strftime('%Y-%m-%d')}")
        label = time_container.find_element(By.XPATH, ".//label") 
        # get time
        time_ms = int(label.get_attribute("for").replace("slot-", ""))
        time = datetime.fromtimestamp(time_ms/ 1000).time()
        test_slot = datetime.combine(day.date(), time)
        print(f"earliest availabe slot is ", test_slot)
        self._logger.info(f"earliest availabe slot is ", test_slot)

        # check if short_notice
        # short_notice = (
        #     label.get_attribute("for").get_attribute("data-short-notice") == "true"
        # )
        randsleep(1)
        try:
            shortNoticeCheck = label.get_attribute('for').get_attribute('data-short-notice')
            if shortNoticeCheck == "true":
                shortNotice = True
                print("Short notice")
            else:
                shortNotice = False
        except:
            shortNotice = False



        # add error handling here if required.
        randsleep(1)
        # click on time box
        first_available_time = time_container.find_element(By.XPATH, "./label")
        randsleep(1)
        first_available_time.click()
        randsleep(1)
        #click on continue button
        continue_button = browser.find_element(By.ID, "slot-chosen-submit")
        randsleep(1)
        continue_button.click()
        # label.click()
        randsleep(1)

        # # click on time container
        # time_container.click() # why are doing this
        # randsleep(0.1)

        # go for it
        # browser.find_element_by_id("slot-warning-continue").click()
        randsleep(1)
        # gets to here
        # dismiss warning
        if shortNotice:
            if self.short_notice:
                browser.find_element(
                    By.XPATH, "(//button[@id='slot-warning-continue'])[2]"
                ).click()
            else:
                self.logger.info("Skipping test as short notice.")
                return None
        else:
            # click submit button
            slot_warning_continue_button = browser.find_element(By.ID, "slot-warning-continue")
            slot_warning_continue_button.click()
        randsleep(5)


        print("15 min timer started @ ")
        self._logger.info("15 min timer started, releases in about 16.5 min ")
        # this is wrapped in a loop in the original code.  I'm not sure what those multiple attempts are for.
        randsleep(3)
        # we are the candidate
        browser.find_element(By.ID, "i-am-candidate").click()
        randsleep(1)

        # we make no manual attempt to solve the captcha here.  It might be
        # solved for us by the Browser().
        if "no longer available" in browser.page_source:
            self.logger.info("Missed it: someone else got there first...")
            return False
        print(f"resereved date is {test_slot}")
        msg = "resereved date is "
        twilio_text(msg, test_slot)
        playsound('C:\\git\\new\\YADC-master\\Alarm01.wav')
        # start of new hold loop
        #sleep for long time while dvsa release back to pool
        # randsleep(950) # was 950
        sleeper() # added this to try and make sure captures the release test. the randsleep was too wide

        # find and click abandon change button
        abandon_button = browser.find_element(By.ID, "abandon")
        randsleep(1)
        abandon_button.click()
#ToDo add explicit wait
        # add explicit wait
        # element = WebDriverWait(driver, 10).until \
        #     (EC.element_to_be_clickable((By.ID, "test-centre-change")))
        # driver.find_element_by_id("test-centre-change").click()
        randsleep(2)
        # find and click abandon change button
        abandon_changes_button = browser.find_element(By.ID, "abandon-changes")
        randsleep(1)
        abandon_changes_button.click()
        randsleep(1)
        print("i have released it")
        msg = "i have released it"
        # twilio_text(msg, test_slot)
        print("lets go again")
        randsleep(2)
        # new reserve release from here
        # it doesn't seem to be able to find it again
        return test_slot



    def _scan_for_test(self, browser: Chrome, driver: Driver, centre: Centre):
        cal = browser.find_element(By.CLASS_NAME, "BookingCalendar-datesBody")
        days = cal.find_elements(By.XPATH, ".//td")
        for day in days:
            if "--unavailable" in day.get_attribute("class"):
                continue
            a = day.find_element(By.XPATH, ".//a")
            date = datetime.strptime(a.get_attribute("data-date"), "%Y-%m-%d")
            print("dates available are on: ", date)# jch
            # ToDo this is where the dates before etc is
            before_date =  driver.current_test.date or centre.date # this  i swapped around
            if date.date() >= before_date.date():
                continue
            # if driver.disabled_dates and date in driver.disabled_dates:
            #     continue
            elif date < driver.not_before:
                continue
            elif date > driver.not_after:
                continue
            return date, a

        return None, None

    def __call__(self):
        while True:
            self._logger.info("Starting search loop")

            if self.dvsa_disabled():
                self._logger.info("Website not currently available; sleeping.")

            while self.dvsa_disabled():
                randsleep(60)  # has spinner

            printed = False
            errs = deque([], maxlen=5)

            try:
                with self._browser as browser:
                    while True:
                        for driver in self.drivers:
                            self.find_tests(browser, driver)
                            randsleep(2 * 60) #was 5 * 60, was 1 * 60, 0.5 casused a search limit
#ToDO this is where the sleep in between runs is set
                            # randsleep(5 * 60) was this, changed by jch
            except Exception as e:
                errs.append(monotonic())
                self._logger.exception(e)
                randsleep(17)  # try not to be too predictable jch was 30

            if len(errs) == 5 and errs[-1] - errs[0] < 10 * 60:
                msg = (
                    "Five errors within 10 minutes; "
                    "giving up so this IP doesn't get blacklisted."
                )
                self._logger.error(msg)  # make sure it's displayed, however we handle
                raise ScraperError(msg)
```

### CODE REVIEW

**Comment by chrishat34** [comment]
```ruby
# YADC Public login
# Uses YADC code and extend it to hold the 1st available test
# Then releases it in a perpetual loop

import logging
from datetime import datetime
import coloredlogs
from pathlib import Path

from browser import Browser, TorBrowser
from scraper import Driver, Scraper, Test, Centre

logging.basicConfig(level=logging.DEBUG)
coloredlogs.install()


def notify(msg):
    """Put notification code here."""
    pass


# define a driver.  You can define as many as you like.
driver = Driver(
    client_name_booked="",
    licence_number="",
    client_name_search="",
    booking_ref="",
    not_before=datetime(2022, 1, 26),
    not_after=datetime(2022, 7, 15),
    centres=[
        # Centre(centre="scunthorpe"),
        Centre(centre="wellingborough"),
        Centre(centre="wellingborough"),
        Centre(centre="Wellingborough"),
        Centre(centre="Wellingborough"),
        Centre(centre="Wellingborough"),
        # Centre(centre="kettering"),
        #Centre(centre="kettering", before=datetime(2022, 5, 2)),
        # Centre(centre="Wellingborough", before=datetime(2023, 1, 1)),  
        # Centre(centre="Northampton", before=datetime(2023, 1, 1)),
    ],
)

# get a scraper for a driver or drivers.
s = Scraper(
                    TorBrowser(
                                        buster=Path('C:\\25-11-2021_dev\\buster'),
                                        chrome='C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe',
                                        chromedriver='C:\\25-11-2021_dev\\YADC-master\\chromedriver.exe',
                                        tor='C:\\25-11-2021_dev\\Tor_Browser\\Browser\\TorBrowser\\Tor\\tor.exe',
                       ),
                     [driver],
                     notify=notify
)
s()
```

**Comment by 2e0byo** [comment]
Ignore the test suite; it doesn't run atm because we need a real (non headless) browser.  so the failed tests in CI don't matter.

**Comment by 2e0byo** [comment]
> Hi, Couldn't work out how to upload just the file so added here

FYI you've opened a PR against my own booking branch.  what you'd normally do is work on your github (your branch), and then PR that.   Not to worry: I'll close this PR and open a new one with a branch with your changes, and take it from there.  Thanks!

**Comment by 2e0byo** [comment]
right!  Going through the changes now; nicely clear, thank you.  I'll not push them as they are and then review them and change them, I'll just fixup as I go.  Will ping you in the new PR when it's done.

**Pull request closed without merging**
